services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    networks:
      - my_network
    restart: unless-stopped

  # postgres:
  #   image: postgres:16
  #   container_name: postgres_container
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./database/postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - my_network
  #   restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo_data:/data/db
    networks:
      - my_network
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis_data:/data
    networks:
      - my_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"       # AMQP (ứng dụng dùng)
      - "15672:15672"     # Web UI
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
